db:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: pass
  driver: org.postgresql.Driver

dialect: org.hibernate.dialect.PostgreSQL95Dialect

hibernate:
  show_sql: true
  format_sql: true
  hbm2ddl.auto: update
  default_schema: clevertec_storage


